print("Welcome to your Monthly Budget")
name = input("Whats is your name?")
print("Welcome" " " + name + "!")
space = ("="*45)
input1 = input("Enter Item 1: ")
monthly1 = float(input("Enter Item 1 Monthly Amount: "))
yearly1 = monthly1 * 12
print("Annual Amounnt Item 1: ${:.2f}".format(yearly1))
print('-'*45)
input2 = input("Enter Item 2: ")
monthly2 = float(input("Enter Item 2 Monthly Amount: "))
yearly2 = monthly2 * 12
print("Annual Amount Item 2: ${:.2f}".format(yearly2))
print('-'*45)
input3 = input("Enter Item 3: ")
monthly3 = float(input("Enter Item 3 Monthly Amount: "))
yearly3 = monthly3 * 12
print("Annual Amount Item 3: ${:.2f}".format(yearly3))
print('-'*45)
input4 = input("Enter Item 4: ")
monthly4 = float(input("Enter Item 4 Monthly Amount: "))
yearly4 = monthly4 * 12
print("Annual Amount Item 4: ${:.2f}".format(yearly4))
print('-'*45)
input5 = input("Enter Item 5: ")
monthly5 = float(input("Enter Item 5 Monthly Amount: "))
yearly5 = monthly5 * 12
print("Annual Amount Item 5: ${:.2f}".format(yearly5))
print('='*45)
print("MONTHLY BUDGET")
print('='*45)
print ("{:<15}{:<15}{:<15}".format('Item','Month','Year'))
print('-'*45)
print ("{:<15}${:<15}${:<15}".format(input1,monthly1,yearly1))
print ("{:<15}${:<15}${:<15}".format(input2,monthly2,yearly2))
print ("{:<15}${:<15}${:<15}".format(input3,monthly3,yearly3))
print ("{:<15}${:<15}${:<15}".format(input4,monthly4,yearly4))
print ("{:<15}${:<15}${:<15}".format(input5,monthly5,yearly5))
print ('-'*45)
