print("SAPOROSA PIZZA")

name = input("Whats is your name?")
space = (" ")

print("Welcome" + space + (name)  +  "!")
print(" ")
print("\033[31m"+"This is our Pizza Menu!")
print("")
print("Pepperoni Pizza - $5.00")
print("Ingredients: Pepperoni, cheese, sauce, and crust")
print(" ")
print("Olive Pizza - $6.00")
print("Ingredients: Olives, cheese, sauce, and crust")
print(" ")
print("Bacon Pizza - $8.00")
print("Ingredients: Bacon, cheese, sauce and crust")
print(" ")
print("Five Cheeses - $12.00")
print("Ingredients: Muzzarela, Gorgonzola, Provolone, Parmesan, Catupiry and crust ")
print(" ")
print("Margherita - 20.00")
print("Ingredients: Tomato sauce, muzzarella, basil, salt, olive oil and crust")
